name: armhf build

on:
  push:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  armhf:
    name: build-armhf
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Deps
      run: sudo apt install gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf
    - name: Build
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=$(which arm-linux-gnueabihf-g++-8) -DCMAKE_C_COMPILER=$(which arm-linux-gnueabihf-gcc-8) 
        make -j$(nproc)
    - name: Make Debian Package
      run: |
        cd ${{ github.workspace }}/build
        make package
    - name: Build Debian package
      uses: dawidd6/action-debian-package@v1
      with:
        # Optional, relative to workspace directory
        source_directory: ${{ github.workspace }}
        # Optional, relative to workspace directory
        artifacts_directory: ${{ github.workspace }}/build
        # Optional, target architecture, defaults to amd64
        cpu_architecture: armhf
        
